[build]
  Command = "npm run build"
  functions = "functions"
  publish = "dist"
[template.environment]
  CONNPASS_SERIES_ID = "change me for your secret token"
  FRONT_API_URL = "set the url to your custom logo here"
